### ISSUE TITLE
HU01 - Consultar catálogo de álbumes

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#1]
## Nombre
Consultar catálogo de álbumes
## Épica
Gestión de álbumes
## Descripción:
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger los que más me interesan
## Criterios de aceptación

- [x] Mostrar listado de albumes en forma de lista ascendente
- [x] Mostrar dentro de cada album, la imagen, el nombre y el genero
- [ ] Cuando se reciba una lista de álbumes vacia, se debe presentar un mensaje de texto que indique **"No hay álbumes disponibles"**
- [x] No debe tener álbumes repetidos
- [x] Mostrar una lista de álbumes que pueda ser contenida en la pantalla, en caso contrario mostrar varias listas seleccionables
- [ ] Se debe incluir el boton de agregar albumes
- [x] Al dar click sobre el album debe llevar al detalle del album

### Mockup
![menuAlbumListBotton](https://user-images.githubusercontent.com/99548876/197227364-9fc10c2b-6ce1-4500-8e55-0ce865c56c36.JPG)
![albumList](https://user-images.githubusercontent.com/99548876/197239306-97385abc-c86f-4774-b9d4-1c0cac5b5df7.JPG)

## Responsable
- Gustavo Romero
- Hassler Isaac
## Puntos de HU estimado
4
 
## Milestone
Sprint 1

### Tiempo estimado
16 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
