### ISSUE TITLE
HU08 - Asociar tracks con un álbum

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#10]
## Nombre
Asociar tracks con un álbum
## Épica
Gestión de álbumes
## Descripción:
Como coleccionista quiero agregar tracks a un álbum para actualizar el catálogo
## Criterios de aceptación

- [x] Se debe mostrar un combo-box con los tracks disponibles
- [x] Se debe mostrar un combo-box con los albumes disponibles para asignar el track
- [x] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

### Mockup
![detalleAlbum](https://user-images.githubusercontent.com/99548876/197241076-da28f956-3ad4-4b7d-8bfe-e14bcf6e2886.JPG)
![asosiateTrackvsAlbum](https://user-images.githubusercontent.com/99548876/197241088-e7cb9e48-f3c1-43a3-ae9c-b7a67e0b64fa.JPG)

## Puntos de HU estimado
4

## Milestone
Sprint 3

### Tiempo estimado
16 horas
## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear formulario para captura de datos requeridos para asignar una cancion al album seleccionado
- [x] Crear validaciones para evitar que los campos se envien vacios o con seleccion por defecto
- [x] Crear servicio
- [x] Consumir backend
- [x] Crear peticion a end point del backend de vinilos con los datos del formulario recopilados y validados
