### ISSUE TITLE
HU02 - Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#2]
## Nombre
Consultar la información detallada de un álbum
## Épica
Gestión de álbumes
## Descripción:
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él
## Criterios de aceptación

- [x] Se debe visualizar el album con los siguientes campos:
  - [x] Nombre
  - [x] Imagen
  - [x] Fecha de lanzamiento
  - [x] Descripción
  - [x] Género
  - [x] Sello disquero
- [x] Se debe habilitar el botón de volver para ver todos los álbumes
- [x] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

### Mockup
![albumList](https://user-images.githubusercontent.com/99548876/197239432-191f9d54-aef4-47de-84e9-e0173fbb1a6f.JPG)
![detalleAlbum](https://user-images.githubusercontent.com/99548876/197227995-7c2d1101-af17-4d78-8ba1-531c508ea5c2.JPG)

## Responsable
- Luis Felipe Cruz
- Edinson Morales

## Puntos de HU estimado
4

## Milestone
Sprint 1

### Tiempo estimado
16 horas
## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
