### ISSUE TITLE
HU03 - Consultar el listado de artistas

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#5]
## Nombre
Consultar el listado de artistas
## Épica
Gestión de artistas
## Descripción
Como usuario visitante quiero ver el listado de artistas para escoger lo que más me interesan
## Criterios de aceptación

- [x] Mostrar listado de artistas en forma de lista ascendente
- [x] Mostrar dentro de cada artista, la imagen y el nombre
- [ ] Cuando se reciba una lista de artistas vacia, se debe presentar un mensaje de texto que indique **"No hay artistas disponibles"**
- [x] No debe tener artistas repetidos
- [x] Mostrar una lista de artistas que pueda ser contenida en la pantalla, en caso contrario mostrar varias listas seleccionables
- [x] Al dar click sobre el artista debe llevar al detalle del artista

### Mockup
![menuAlbumListBotton](https://user-images.githubusercontent.com/99548876/197229915-3037eef4-3560-4d34-9f0b-a6aabf631832.JPG)
![ArtistList](https://user-images.githubusercontent.com/99548876/197240433-33a76469-55bb-4239-9084-38400720e8d8.JPG)

## Puntos de HU estimado
2

## Milestone
Sprint 2

### Tiempo estimado
8 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
