### ISSUE TITLE
HU04 - Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#6]
## Nombre
Consultar la información detallada de un artista
## Épica
Gestión de artistas
## Descripción
Como usuario visitante quiero vel el detalle de un artista para ampliar la infoirmación sobre él
## Criterios de aceptación

- [x] Se debe visualizar el artista con los siguientes campos:
  - [x] Nombre
  - [x] Imagen
  - [x] Descripción
  - [x] Fecha de nacimiento
- [x] Se debe habilitar un botón para volver a ver todos los artistas
- [x] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

### Mockup
![ArtistList](https://user-images.githubusercontent.com/99548876/197240664-45a1dbc8-2e21-49a5-91fb-001ea844385c.JPG)
![detalleArtist](https://user-images.githubusercontent.com/99548876/197230286-c07085e9-f751-4a8b-b4bc-7a8ec0da4d2f.JPG)

## Puntos de HU estimado
3

## Milestone
Sprint 2

### Tiempo estimado
12 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
