### ISSUE TITLE
HU05 - Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#7]
## Nombre
Consultar listado de coleccionistas
## Épica
Gestión de coleccionistas
## Descripción
Como usuario visitante quiero consultar el listado de colecciones para seleccionar el que más me interese
## Criterios de aceptación

- [x] Mostrar listado de coleccionistas en forma de lista ascendente
- [x] Mostrar dentro de cada coleccionista, el nombre y una imagen prestablecida, para mantener el diseño de la aplicación
- [x] Cuando se reciba una lista de coleccionistas vacia, se debe presentar un mensaje de texto que indique **"No hay coleccionistas disponibles"**
- [x] No debe tener coleccionistas repetidos
- [x] Mostrar una lista de coleccionistas que pueda ser contenida en la pantalla, en caso contrario mostrar varias listas seleccionables

### Mockup
![menuAlbumListBotton](https://user-images.githubusercontent.com/99548876/197231529-e4856a1b-cb81-47d4-a83f-f44900ccb65e.JPG)
![CollectionList](https://user-images.githubusercontent.com/99548876/197231546-58d7e782-0889-471e-9471-c2fe0748d753.JPG)

## Puntos de HU estimado
2

## Milestone
Sprint 2

### Tiempo estimado
8 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
