### ISSUE TITLE
HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#8]
## Nombre
Consultar la información detallada de coleccionista
## Épica
Gestión de coleccionista
## Descripción
Como usuario vistante quiero ver el detalle de un coleccionista para conocer sus gustos musicales
## Criterios de aceptación

- [x] Se debe visualizar el coleccionista con los siguientes campos:
  - [x] Nombre
  - [x] Teléfono
  - [x] email
  - [ ] Álbumes (Listado)
- [x] Se debe habilitar un botón para volver a ver todos los coleccionistas
- [x] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

## Puntos de HU estimado
3

## Milestone
Sprint 3

### Tiempo estimado
12 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Nombre
Consultar la información detallada de coleccionista
## Épica
Gestión de coleccionista
## Descripción
Como usuario vistante quiero ver el detalle de un coleccionista para conocer sus gustos musicales
## Criterios de aceptación

- [x] Se debe visualizar el coleccionista con los siguientes campos:
  - [x] Nombre
  - [x] Teléfono
  - [x] email
  - [x] price
  - [x] status
  - [ ] Álbumes (Listado)
- [ ] Se debe habilitar un botón para volver a ver todos los coleccionistas
- [ ] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

### Mockup
![CollectionList](https://user-images.githubusercontent.com/99548876/197231843-ed2f9214-0553-4ce7-b7cb-af3664d63927.JPG)
![CollectionDetail](https://user-images.githubusercontent.com/99548876/197231827-9f47b4b6-9830-437b-979f-cfd8c7839a7d.JPG)

## Puntos de HU estimado
3

## Milestone
Sprint 3

### Tiempo estimado
12 horas

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear servicio
- [x] Consumir backend
