### ISSUE TITLE
HU07 - Crear un álbum

### ISSUE THREAD

**Issue by gromeron** [gromeron/MISW-4203-Aplicaciones-moviles#9]
## Nombre
Crear un álbum
## Épica
Gestión de álbumes
## Descripción:
Como coleccionista quiero agregar un álbum al listado
## Criterios de aceptación

- [x] Se deben visualizar los siguientes campos:
  - [x] Nombre
  - [x] Imagen (url de la imágen del álbum en el formulario)
  - [x] Fecha de lanzamiento
  - [x] Descripción
  - [x] Género
  - [x] Sello disquero
- [x] Ningún campo debe estar vacío al momento de ejecutar la acción de crear álbum
- [x] El campo nombre no debe tener menos de 1 caracteres
- [x] El campo descrpción no puede tener mas de 600 caracteres
- [x] No deben haber álbumes con nombres repetidos
- [x] La interfaz gráfica de la página debe adaptarse al tamaño de la pantalla del dispositivo

### Mockup
![albumList](https://user-images.githubusercontent.com/99548876/197238712-219a2f59-4906-4eb6-bc36-2baf95ed83ab.JPG)
![createAlbum](https://user-images.githubusercontent.com/99548876/197238726-984c8056-1ec9-4f8c-b7fe-47a853f57104.JPG)

## Puntos de HU estimado
5

## Milestone
Sprint 3

### Tiempo estimado
20 h

## Revisión:

Criterios | Descripción | Estado
--- | --- | ---
Completo | Cubre totalmente las funcionalidades solicitadas en el enunciado y contiene lo necesario para cumplir con su objetivo | Cumple satisfactoriamente  
Consistente | En la HU no se presentan contradicciones o inconsistencias | Cumple satisfactoriamente  
Negociable | Se ha determinado para la historia si es necesaria o deseable | Cumple satisfactoriamente  
Valiosa | La historia genera valor al producto y a sus posibles usuarios | Cumple satisfactoriamente  
Estimable | Se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida |Cumple satisfactoriamente  
Pequeña | La historia no requiere más de 2 días para ser desarrollada por una persona | Cumple satisfactoriamente
Comprobable (se puede verificar / probar) | La descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia | Cumple satisfactoriamente

## Subtareas
- [x] Crear archivo activity para la vista
- [x] Crear archivo kotlin para la logica
- [x] Crear la vista en código XML
- [x] Crear formulario para captura de datos requeridos para creacion de un album
- [x] Crear validaciones para evitar que los campos se envien vacios
- [x] Crear validaciones de tipos de datos para cada uno de los campos
- [x] Crear servicio
- [x] Consumir backend
- [x] Crear peticion a end point del backend de vinilos con los datos del formulario recopilados y validados
